### ISSUE TITLE
Is having inspector be a separate thing worth the maintenance burden?

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/interactors#132]
When we added the ability to introspect interactors, we didn't want to provide a method for fetching matching elements on an interactor, something like this:

```js
let elements = await Button("Foo").all();
```

Instead we opted to create an inspector API like this:

```js
let elements = createInspector(Button, document.body).all();
```

I don't remember the exact use-case that we added this for. Is it even still relevant?

At any case, the infrastructure needed to support this feature is quite expensive. Our types are already very complicated, and this feature further complicates them. We should be asking ourselves if this overhead is worth it. If we want to have this feature available, maybe a simpler API with a smaller API surface would do the trick as well, and we wouldn't have to complicate our types. Just some thinking as I was working on simplifying the typing.

**Comment by jnicklas** [comment]
@wKich I think you worked on this, right? Do you remember why we added this? I have a vague memory that you were working on a playground for interactors and that this had something to do with it, but I don't really remember how that panned out?

**Comment by wKich** [comment]
I need the .all method to show in inspector all matched elements. I asked @cowboyd about it and we decided to don't include .all method as a part of interactors API. I think we did it because the interactors must match with only one element.

**Comment by cowboyd** [comment]
The use-case is that we want to have a dynamic and visual way to see what interactors are matching, and what the values of their filters / locators are just by presenting them to a document. 

These tools are really key in helping you "grok" how an interaction library works by letting you compare alternatives with an instant feedback loop.

Examples from other tools:

* testing-library https://testing-playground.com
* cypress: https://docs.cypress.io/guides/core-concepts/test-runner#Selector-Playground

I guess my questions are: 1) What is expensive about it? 2) can we refactor internals to make it less so, and 3) can we accomplish the use-case with a completely separate mecahnism?

**Comment by jnicklas** [comment]
@cowboyd it is "expensive" in this sense of course figuratively, because we have a very high cognitive burden on our types. I wrote them, and when I've been away for a little while from this project, I barely understand them anymore 😅 The inspector API further complicates these types (for example by splitting `Interactor` into `BaseInteractor` and ` ExistsAssertionsImplementation`), and it would be great to streamline this and simplify it. So the question it, can we build an inspector API which does *not* complicate our types?

**Comment by cowboyd** [comment]
One thing that occurred to me as I was having a look at this https://github.com/folio-org/stripes-testing/pull/140/files was that there is a case where they want to make assertions against multiple elements, in this case "all actions are enabled", or run an action against a set of interactors as in "check all of the filters". Using a "higher order interactor"  may be the way to accomplish this. This would be similar to the `.all()` solution Dmitriy proposed earlier, except I think by modeling `All` as an interaction itself might solve some of the issues?

```ts
import { All } from '@interactors/html';

await All(Button('Submit')).is({ disabled: true }))
await All(FieldSet('Filters').find(Checkbox()).click();

//useful to inspector
let buttonElements = await All(Button()).elements();
```

I'm not sure how this would effect the typing although it seems doable since `All<T>` would just be `T & AllAPI`. Where `AllAPI` is any extra filters that we want to add like the `elements` filter above.

But zooming out a couple thousand feet, I think that the core functionality needed for the inspector is basically these functions:

**interactor -> HTMLNodeList**
This is needed to highlight the elements in the DOM that are matched by the class of interactor

**HTMLElement -> Interactor[]**
This is the reverse operation, where if you are hovering over an element, we want to be able to highlight all of the interactors that match it.

**Comment by wKich** [comment]
The reason why split Interactor and added BaseInteractor, because there is no way to use a different resolver than the default one `unsafeSyncResolveUnique`. So we can't use `All` interactor because we can't change the resolver from the outside.

**Comment by jnicklas** [comment]
I think #139 solves this sufficiently well
